mesh: "fsm"
telemetry_mode: "fsm"
conn:
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
qps:
    - 1000
duration: 240
metrics:
    - p50
    - p90
    - p99
    - p999
perf_record: false
run_bothsidecar: true
run_serversidecar: false
run_clientsidecar: false
run_baseline: true

jitter: true